import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('th');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  th: {
    // Profile Page
    'profile.title': 'โปรไฟล์และการตั้งค่า',
    'profile.email': '📧',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.fullName': 'ชื่อ-นามสกุล',
    'profile.age': 'อายุ (ปี)',
    'profile.weight': 'น้ำหนัก (kg)',
    'profile.height': 'ส่วนสูง (cm)',
    'profile.updateProfile': 'บันทึกเว็บไซต์แก้ไขเพิ่มเติม',
    'profile.notificationSettings': 'การตั้งค่าเตือน',
    'profile.fastingAlert': 'แจ้งเตือนเว้นอาหาร',
    'profile.fastingAlertDesc': 'เตือนให้เว็บไซต์รับการมีอาหารของคุณ',
    'profile.activityAlert': 'แจ้งเตือนกับการกีฬาของคุณ',
    'profile.activityAlertDesc': 'เตือนให้บันทึกเว็บไซต์การกีฬาของคุณ',
    'profile.mealAlert': 'แจ้งเตือนสั่งซื้อเมื่อ',
    'profile.mealAlertDesc': 'เตือนเมื่อสั่งซื้อเข้าเว็บ',
    'profile.privacySettings': 'ความเป็นส่วนตัวของคุณเว้นอาหารของคุณ',
    'profile.setGoals': 'สร้างและตั้งค่าเป้าหมาย',
    'profile.aboutTracker': 'เพิ่มเติม Longevity Tracker',
    'profile.logout': 'ออกจากระบบ',
    'profile.version': 'เวอร์ชัน',
    'profile.language': 'ภาษา',
    'profile.languageThai': '🇹🇭 ไทย',
    'profile.languageEnglish': '🇬🇧 English',
    'editProfile.status': 'โปรไฟล์',
    'editProfile.title': 'แก้ไขข้อมูลส่วนตัว',
    'editProfile.save': 'บันทึก',
    'editProfile.saved': 'บันทึกข้อมูลเรียบร้อยแล้ว',
    'editProfile.fullName': 'ชื่อ-นามสกุล',
    'editProfile.fullNamePlaceholder': 'กรอกชื่อ-นามสกุล',
    'editProfile.email': 'อีเมล',
    'editProfile.emailPlaceholder': 'กรอกอีเมล',
    'editProfile.birthDate': 'วันเกิด',
    'editProfile.gender': 'เพศ',
    'editProfile.select': 'เลือก',
    'editProfile.male': 'ชาย',
    'editProfile.female': 'หญิง',
    'editProfile.other': 'อื่นๆ',
    'editProfile.height': 'ส่วนสูง (cm)',
    'editProfile.heightPlaceholder': 'เช่น 170',
    'editProfile.weight': 'น้ำหนัก (kg)',
    'editProfile.weightPlaceholder': 'เช่น 65',
    'editProfile.phone': 'เบอร์โทรศัพท์',
    'editProfile.phonePlaceholder': 'เช่น 08X-XXX-XXXX',
    'editProfile.address': 'ที่อยู่',
    'editProfile.addressPlaceholder': 'บ้านเลขที่ ถนน ตำบล อำเภอ จังหวัด รหัสไปรษณีย์',
    'editProfile.country': 'ประเทศ',
    'editProfile.countryPlaceholder': 'ประเทศ',
    'editProfile.idType': 'ประเภทเอกสาร',
    'editProfile.nationalId': 'บัตรประชาชน',
    'editProfile.passport': 'พาสปอร์ต',
    'editProfile.nationalIdNumber': 'เลขบัตรประชาชน',
    'editProfile.passportNumber': 'หมายเลขพาสปอร์ต',
    'editProfile.nationalIdPlaceholder': 'กรอกเลขบัตรประชาชน',
    'editProfile.passportPlaceholder': 'กรอกหมายเลขพาสปอร์ต',

    // Home Page
    'home.title': 'Longevity Passport',
    'home.greeting': 'สวัสดี',
    'home.greetingSubtext': 'วันนี้รู้สึกอย่างไร',
    'home.longevityScore': 'คะแนนสุขภาพ Longevity',
    'home.sleep': 'การนอนหลับ',
    'home.nutrition': 'โภชนาการ',
    'home.fasting': 'การเว้นอาหาร',
    'home.activity': 'กิจกรรม',
    'home.foodRecognition': 'ถ่ายรูปอาหาร',
    'home.fastingTimer': 'ตัวจับเวลาเว้นอาหาร',
    'home.dailyTip': 'คำแนะนำของวันนี้',
    'home.dailyTipText': 'คุณนอนหลับได้น้อย ลองเข้านอนให้เร็วขึ้น 30 นาทีคืนนี้',
    'home.tip1': 'ดื่มน้ำเปล่า 8 แก้วต่อวัน เพื่อให้ร่างกายหลับสนิทสุขภาพดี',
    'home.tip2': 'เดินเท้าวันละ 30 นาที ช่วยป้องกันโรคหัวใจและเบาหวาน',
    'home.tip3': 'กินผักสดทุกมื้ออาหาร อุดมไปด้วยวิตามินและใยอาหาร',
    'home.tip4': 'นอนหลับเวลา 22:00 น. ถึง 6:00 น. เพื่อสุขภาพที่ดี',
    'home.tip5': 'อดอาหาร 16 ชั่วโมง สวนโปรตีน 8 ชั่วโมง ช่วยปรับฮอร์โมน',
    'home.tip6': 'ออกอดออกกำลังกาย 30 นาทีทุกเช้า เพิ่มระดับพลังงาน',
    'home.tip7': 'หลีกเลี่ยงหน้าจออย่างน้อย 1 ชั่วโมงก่อนนอน',
    'home.todaySummary': 'สรุปวันนี้',
    'home.ifToday': 'IF วันนี้',
    'home.days': 'วัน',
    'home.lastUpdated': 'อัปเดตล่าสุด',
    'home.quickActions': 'เครื่องมือ',
    'home.food': 'อาหาร',
    'home.exercise': 'ออกกำลังกาย',
    'home.fastingTime': 'เวลาเว้นอาหาร',
    'home.hours': 'ชั่วโมง',
    'home.calories': 'แคลอรี่',
    'home.kcal': 'kcal',
    'home.steps': 'ก้าว',
    'home.water': 'น้ำ',
    'home.glasses': 'แก้ว',

    // Navigation
    'nav.home': 'หน้าหลัก',
    'nav.fasting': 'อาหาร',
    'nav.dashboard': 'สถิติ',
    'nav.team': 'ทีม',
    'nav.profile': 'โปรไฟล์',

    // Login Page
    'login.welcome': 'ยินดีต้อนรับ',
    'login.welcomeText1': 'เริ่มต้นเส้นทางสุขภาพ',
    'login.welcomeText2': 'ดีของคุณ',
    'login.subtitle': 'เข้าสู่ระบบเพื่อติดตามเส้นทางสุขภาพของคุณ',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.forgotPassword': 'ลืมรหัสผ่าน?',
    'login.loginButton': 'เข้าสู่ระบบ',
    'login.noAccount': 'ยังไม่มีบัญชี?',
    'login.register': 'สมัครสมาชิก',

    // Fasting Page
    'fasting.title': 'การเว้นอาหาร',
    'fasting.currentStatus': 'สถานะปัจจุบัน',
    'fasting.fasting': 'กำลังเว้นอาหาร',
    'fasting.eating': 'ช่วงรับประทานอาหาร',
    'fasting.elapsed': 'เวลาที่ผ่านไป',
    'fasting.remaining': 'เวลาคงเหลือ',
    'fasting.start': 'เริ่ม',
    'fasting.end': 'สิ้นสุด',
    'fasting.achievement': 'ความสำเร็จรายวัน',
    'fasting.achievementText': 'คุณทำการอดอาหารสำเร็จ 3 ครั้งในสัปดาห์นี้!',

    // Dashboard Page
    'dashboard.title': 'แดชบอร์ดส่วนตัว',
    'dashboard.overallStats': 'ค่าแนวรวม',
    'dashboard.orders': 'คำสั่งซื้อ',
    'dashboard.day': 'วัน',
    'dashboard.week': 'สัปดาห์',
    'dashboard.month': 'เดือน',
    'dashboard.sampleDate': '16 มิ.ย.',
    'dashboard.monthJan': 'ม.ค.',
    'dashboard.monthFeb': 'ก.พ.',
    'dashboard.monthMar': 'มี.ค.',
    'dashboard.monthApr': 'เม.ย.',
    'dashboard.monthJun': 'มิ.ย.',
    'dashboard.monthJul': 'ก.ค.',
    'dashboard.monthAug': 'ส.ค.',
    'dashboard.monthSep': 'ก.ย.',
    'dashboard.monthOct': 'ต.ค.',
    'dashboard.monthNov': 'พ.ย.',
    'dashboard.monthDec': 'ธ.ค.',
    'dashboard.summary': 'สรุปและคำแนะนำ',
    'dashboard.sleep': 'การนอน',
    'dashboard.sleepDesc': 'ดีมาก! คุณนอนหลับได้เต็มที่ 7.8 ชั่วโมง/คืน',
    'dashboard.nutrition': 'โภชนาการ',
    'dashboard.nutritionDesc': 'ต่ำพอใช้และผลไม่ดีโดยโภชนาการ',
    'dashboard.fasting': 'Intermittent Fasting',
    'dashboard.fastingDesc': 'ดีมากแล้ว/ คุณทำ IF สำเร็จแล้ว',
    'dashboard.exercise': 'การออกกำลังกาย',
    'dashboard.exerciseDesc': 'พยายามออกกำลังกายเพิ่มขึ้นอีก 10 นาที/วัน',
    'dashboard.status.excellent': 'ยอดเยี่ยม',
    'dashboard.status.good': 'ดี',
    'dashboard.status.fair': 'พอใช้',
    'dashboard.status.poor': 'ต้องปรับปรุง',
    'dashboard.sleep.excellent': 'ดีมาก! คุณนอนหลับใกล้เคียง 7–9 ชั่วโมง/คืนอย่างสม่ำเสมอ',
    'dashboard.sleep.good': 'การนอนดีแล้ว ลองรักษาเวลานอนให้สม่ำเสมอ',
    'dashboard.sleep.fair': 'นอนหลับยังไม่คงที่ ลองเข้านอนเร็วขึ้น 30 นาที',
    'dashboard.sleep.poor': 'การนอนยังต่ำ ลองลดหน้าจอก่อนนอนและตั้งเวลานอนให้ชัดเจน',
    'dashboard.nutrition.excellent': 'โภชนาการยอดเยี่ยม เลือกอาหารสมดุลต่อเนื่อง',
    'dashboard.nutrition.good': 'โภชนาการดี ลองเพิ่มผักและโปรตีนคุณภาพสูง',
    'dashboard.nutrition.fair': 'โภชนาการพอใช้ ลดอาหารหวาน/ทอดและเพิ่มไฟเบอร์',
    'dashboard.nutrition.poor': 'โภชนาการต้องปรับปรุง เริ่มจากมื้อเล็กที่สมดุล',
    'dashboard.fasting.excellent': 'เยี่ยมมาก! คุณทำ IF ได้สม่ำเสมอ',
    'dashboard.fasting.good': 'ทำได้ดี ลองรักษาระยะเวลา IF ให้คงที่',
    'dashboard.fasting.fair': 'เริ่มได้ดี ลองเพิ่มความสม่ำเสมอในการอดอาหาร',
    'dashboard.fasting.poor': 'ยังไม่ได้เริ่ม IF ลองตั้งเป้าหมายแบบ 14:10 ก่อน',
    'dashboard.activity.excellent': 'กิจกรรมยอดเยี่ยม รักษาความสม่ำเสมอไว้',
    'dashboard.activity.good': 'กิจกรรมดี เพิ่มเวลาอีกเล็กน้อยจะยิ่งดี',
    'dashboard.activity.fair': 'กิจกรรมยังน้อย ลองเดินเพิ่มวันละ 10–15 นาที',
    'dashboard.activity.poor': 'เริ่มขยับร่างกายวันละ 10 นาทีเพื่อเริ่มต้น',
    'dashboard.weekly': 'รายสัปดาห์',
    'dashboard.monthly': 'รายเดือน',

    // Team Page
    'team.title': 'ทีมและการกีฬา',
    'team.members': 'Members',
    'team.teamScore': 'Team\'s Longevity Score',
    'team.challengeTitle': '7-Day Wellness Challenge',
    'team.challengeDesc': 'กำลังระบบสุขภาพฟรีของคุณแล้วโฟลเข้าร่วมการท้าทาย',
    'team.joinChallenge': 'เข้าร่วมกัน!',
    'team.leaderboard': 'Leaderboard',
    'team.myTeam': 'My Team',
    'team.allTeams': 'All Teams',
    'team.challenges': 'ความท้าทาย',

    // Food Recognition
    'food.title': '🍽️ ถ่ายรูปอาหาร',
    'food.loading': 'กำลังโหลดโมเดล...',
    'food.openCamera': '📷 เปิดกล้อง',
    'food.selectImage': '🖼️ เลือกรูปภาพ',
    'food.capture': '📸 ถ่ายรูป',
    'food.cancel': 'ยกเลิก',
    'food.analyzing': 'กำลังวิเคราะห์...',
    'food.results': 'ผลการวิเคราะห์:',
    'food.retake': 'ถ่ายใหม่',
    'food.save': 'บันทึกข้อมูล',
    'food.logMeal': 'บันทึกมื้ออาหาร',
    'food.mealLogged': 'บันทึกมื้ออาหารเรียบร้อยแล้ว',
    'food.padthai': 'ผัดไทย',
    'food.khaoManGai': 'ข้าวมันไก่',
    'food.greenCurry': 'แกงเขียวหวาน',
    'food.friedRice': 'ข้าวผัด',
    'food.papayaSalad': 'ส้มตำ',
    'food.basilFry': 'ผัดกะเพรา',
    'food.khaoSoi': 'ข้าวซอย',
    'food.larbMoo': 'ลาบหมู',
    'food.tomYum': 'ต้มยำกุ้ง',
    'food.omelletRice': 'ข้าวไข่เจียว',

    // Activity Page
    'activity.title': 'การออกกำลังกาย',
    'activity.back': 'กลับ',
    'activity.minutesToday': 'นาทีวันนี้',
    'activity.caloriesBurned': 'แคลอรี่ที่เผาผลาญ',
    'activity.quickLog': 'บันทึกด่วน',
    'activity.walking': 'เดิน',
    'activity.running': 'วิ่ง',
    'activity.cycling': 'ปั่นจักรยาน',
    'activity.strength': 'ฝึกกล้ามเนื้อ',
    'activity.yoga': 'โยคะ',
    'activity.swimming': 'ว่ายน้ำ',
    'activity.history': 'ประวัติการออกกำลังกาย',
    'activity.noActivities': 'ยังไม่มีการบันทึกการออกกำลังกาย',
    'activity.minutes': 'นาที',
    'activity.kcal': 'แคลอรี่',
    'activity.logActivity': 'บันทึกการออกกำลังกาย',
    'activity.duration': 'ระยะเวลา',
    'activity.estimatedCalories': 'แคลอรี่โดยประมาณ',
    'activity.logButton': 'บันทึก',

    // Sleep Page
    'sleep.title': 'การนอนหลับ',
    'sleep.back': 'กลับ',
    'sleep.avgHours': 'ชั่วโมงเฉลี่ย/สัปดาห์',
    'sleep.avgQuality': 'คุณภาพเฉลี่ย',
    'sleep.tipTitle': 'คำแนะนำ',
    'sleep.tip1': 'เริ่มบันทึกการนอนเพื่อติดตามสุขภาพของคุณ',
    'sleep.tip2': 'คุณนอนน้อยเกินไป ควรนอน 7-9 ชั่วโมงต่อคืน',
    'sleep.tip3': 'คุณภาพการนอนต่ำ ลองหลีกเลี่ยงหน้าจอก่อนนอน',
    'sleep.tip4': 'คุณนอนมากเกินไป อาจส่งผลต่อพลังงานในวัน',
    'sleep.tip5': 'ดีมาก! รักษาแบบแผนการนอนนี้ต่อไป',
    'sleep.logSleep': 'บันทึกการนอน',
    'sleep.history': 'ประวัติการนอน',
    'sleep.noLogs': 'ยังไม่มีการบันทึกการนอน',
    'sleep.bedtime': 'เวลาเข้านอน',
    'sleep.waketime': 'เวลาตื่น',
    'sleep.duration': 'ระยะเวลา',
    'sleep.hours': 'ชั่วโมง',
    'sleep.quality': 'คุณภาพการนอน',
    'sleep.excellent': 'ดีเยี่ยม',
    'sleep.good': 'ดี',
    'sleep.fair': 'พอใช้',
    'sleep.poor': 'แย่',
    'sleep.logButton': 'บันทึก',

    // Longevity Score
    'longevity.title': 'คะแนนสุขภาพรายวัน',
    'longevity.score': 'คะแนน',
    'longevity.today': 'วันนี้',
    'longevity.breakdown': 'การแบ่งคะแนน',
    'longevity.nutrition': 'โภชนาการ',
    'longevity.fasting': 'การเว้นอาหาร',
    'longevity.activity': 'การออกกำลังกาย',
    'longevity.sleep': 'การนอนหลับ',
    'longevity.excellent': 'ดีเยี่ยม',
    'longevity.good': 'ดี',
    'longevity.fair': 'พอใช้',
    'longevity.needsImprovement': 'ต้องปรับปรุง',
    'longevity.noData': 'ยังไม่มีข้อมูล',
    'longevity.startTracking': 'เริ่มบันทึกข้อมูลสุขภาพของคุณ',
  },
  en: {
    // Profile Page
    'profile.title': 'Profile & Settings',
    'profile.email': '📧',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.age': 'Age (years)',
    'profile.weight': 'Weight (kg)',
    'profile.height': 'Height (cm)',
    'profile.updateProfile': 'Update Profile Information',
    'profile.notificationSettings': 'Notification Settings',
    'profile.fastingAlert': 'Fasting Reminder',
    'profile.fastingAlertDesc': 'Remind you to track your fasting',
    'profile.activityAlert': 'Activity Reminder',
    'profile.activityAlertDesc': 'Remind you to log your exercise',
    'profile.mealAlert': 'Meal Reminder',
    'profile.mealAlertDesc': 'Remind you when it\'s time to eat',
    'profile.privacySettings': 'Privacy & Fasting Settings',
    'profile.setGoals': 'Set Goals & Targets',
    'profile.aboutTracker': 'About Longevity Tracker',
    'profile.logout': 'Log Out',
    'profile.version': 'Version',
    'profile.language': 'Language',
    'profile.languageThai': '🇹🇭 Thai',
    'profile.languageEnglish': '🇬🇧 English',
    'editProfile.status': 'Profile',
    'editProfile.title': 'Edit Personal Information',
    'editProfile.save': 'Save',
    'editProfile.saved': 'Profile saved successfully',
    'editProfile.fullName': 'Full Name',
    'editProfile.fullNamePlaceholder': 'Enter full name',
    'editProfile.email': 'Email',
    'editProfile.emailPlaceholder': 'Enter email',
    'editProfile.birthDate': 'Date of Birth',
    'editProfile.gender': 'Gender',
    'editProfile.select': 'Select',
    'editProfile.male': 'Male',
    'editProfile.female': 'Female',
    'editProfile.other': 'Other',
    'editProfile.height': 'Height (cm)',
    'editProfile.heightPlaceholder': 'e.g. 170',
    'editProfile.weight': 'Weight (kg)',
    'editProfile.weightPlaceholder': 'e.g. 65',
    'editProfile.phone': 'Phone Number',
    'editProfile.phonePlaceholder': 'e.g. +66XXXXXXXXX',
    'editProfile.address': 'Address',
    'editProfile.addressPlaceholder': 'House no., street, district, province, postal code',
    'editProfile.country': 'Country',
    'editProfile.countryPlaceholder': 'Country',
    'editProfile.idType': 'ID Type',
    'editProfile.nationalId': 'National ID',
    'editProfile.passport': 'Passport',
    'editProfile.nationalIdNumber': 'National ID Number',
    'editProfile.passportNumber': 'Passport Number',
    'editProfile.nationalIdPlaceholder': 'Enter national ID number',
    'editProfile.passportPlaceholder': 'Enter passport number',

    // Home Page
    'home.title': 'Longevity Passport',
    'home.greeting': 'Hello',
    'home.greetingSubtext': 'How are you feeling today',
    'home.longevityScore': 'Longevity Score',
    'home.sleep': 'Sleep',
    'home.nutrition': 'Nutrition',
    'home.fasting': 'IF',
    'home.activity': 'Activity',
    'home.foodRecognition': 'Food Recognition',
    'home.fastingTimer': 'Fasting timer',
    'home.dailyTip': 'Today\'s Tip',
    'home.dailyTipText': 'You slept less. Try going to bed 30 minutes earlier tonight',
    'home.tip1': 'Drink 8 glasses of water daily for better sleep and hydration',
    'home.tip2': 'Walk 30 minutes daily to prevent heart disease and diabetes',
    'home.tip3': 'Eat fresh vegetables at every meal for vitamins and fiber',
    'home.tip4': 'Sleep from 10 PM to 6 AM for optimal circadian rhythm',
    'home.tip5': 'Practice 16:8 fasting to improve metabolic health and hormones',
    'home.tip6': 'Exercise 30 minutes each morning to boost daily energy levels',
    'home.tip7': 'Avoid screens at least 1 hour before bedtime for better sleep quality',
    'home.todaySummary': 'Today\'s Summary',
    'home.ifToday': 'IF Today',
    'home.days': 'Days',
    'home.lastUpdated': 'Last Updated',
    'home.quickActions': 'Quick Actions',
    'home.food': 'The food',
    'home.exercise': 'Exercise',
    'home.fastingTime': 'Fasting Time',
    'home.hours': 'Hours',
    'home.calories': 'Calories',
    'home.kcal': 'kcal',
    'home.steps': 'Steps',
    'home.water': 'Water',
    'home.glasses': 'Glasses',

    // Navigation
    'nav.home': 'Home',
    'nav.fasting': 'Food',
    'nav.dashboard': 'Stats',
    'nav.team': 'Team',
    'nav.profile': 'Profile',

    // Login Page
    'login.welcome': 'Welcome',
    'login.welcomeText1': 'Start your health',
    'login.welcomeText2': 'journey',
    'login.subtitle': 'Sign in to track your health journey',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot password?',
    'login.loginButton': 'Sign in',
    'login.noAccount': 'Don\'t have an account?',
    'login.register': 'Sign Up',

    // Fasting Page
    'fasting.title': 'Intermittent Fasting',
    'fasting.currentStatus': 'Current Status',
    'fasting.fasting': 'Fasting',
    'fasting.eating': 'Eating Window',
    'fasting.elapsed': 'Time Elapsed',
    'fasting.remaining': 'Time Remaining',
    'fasting.start': 'Start',
    'fasting.end': 'End',
    'fasting.achievement': 'Daily Achievement',
    'fasting.achievementText': 'You\'ve completed 3 fasting sessions this week!',

    // Dashboard Page
    'dashboard.title': 'Personal Dashboard',
    'dashboard.overallStats': 'Overall Statistics',
    'dashboard.orders': 'Orders',
    'dashboard.day': 'Day',
    'dashboard.week': 'Week',
    'dashboard.month': 'Month',
    'dashboard.sampleDate': 'June 16',
    'dashboard.monthJan': 'Jan',
    'dashboard.monthFeb': 'Feb',
    'dashboard.monthMar': 'Mar',
    'dashboard.monthApr': 'Apr',
    'dashboard.monthJun': 'Jun',
    'dashboard.monthJul': 'Jul',
    'dashboard.monthAug': 'Aug',
    'dashboard.monthSep': 'Sep',
    'dashboard.monthOct': 'Oct',
    'dashboard.monthNov': 'Nov',
    'dashboard.monthDec': 'Dec',
    'dashboard.summary': 'Summary & Recommendations',
    'dashboard.sleep': 'Sleep',
    'dashboard.sleepDesc': 'Great! You slept a full 7.8 hours/night',
    'dashboard.nutrition': 'Nutrition',
    'dashboard.nutritionDesc': 'Fair but needs improvement in nutrition',
    'dashboard.fasting': 'Intermittent Fasting',
    'dashboard.fastingDesc': 'Great job! You are meeting your IF goals',
    'dashboard.exercise': 'Exercise',
    'dashboard.exerciseDesc': 'Try adding 10 more minutes/day of exercise',
    'dashboard.status.excellent': 'Excellent',
    'dashboard.status.good': 'Good',
    'dashboard.status.fair': 'Fair',
    'dashboard.status.poor': 'Needs Improvement',
    'dashboard.sleep.excellent': 'Excellent! You’re close to 7–9 hours/night consistently',
    'dashboard.sleep.good': 'Good sleep. Keep a steady bedtime routine',
    'dashboard.sleep.fair': 'Sleep is inconsistent. Try going to bed 30 minutes earlier',
    'dashboard.sleep.poor': 'Sleep is low. Reduce screens and set a fixed bedtime',
    'dashboard.nutrition.excellent': 'Great nutrition. Keep meals balanced and consistent',
    'dashboard.nutrition.good': 'Good nutrition. Add more veggies and quality protein',
    'dashboard.nutrition.fair': 'Nutrition is fair. Cut sugary/fried foods and add fiber',
    'dashboard.nutrition.poor': 'Nutrition needs work. Start with one balanced meal',
    'dashboard.fasting.excellent': 'Excellent! You’re consistent with IF',
    'dashboard.fasting.good': 'Good progress. Keep your IF window consistent',
    'dashboard.fasting.fair': 'Nice start. Try to be more consistent with IF',
    'dashboard.fasting.poor': 'Not started yet. Begin with a 14:10 window',
    'dashboard.activity.excellent': 'Excellent activity. Keep the momentum',
    'dashboard.activity.good': 'Good activity. Add a little more time daily',
    'dashboard.activity.fair': 'Activity is low. Add a 10–15 min walk',
    'dashboard.activity.poor': 'Start with 10 minutes of movement daily',
    'dashboard.weekly': 'Weekly',
    'dashboard.monthly': 'Monthly',

    // Team Page
    'team.title': 'Team & Challenges',
    'team.members': 'Members',
    'team.teamScore': 'Team\'s Longevity Score',
    'team.challengeTitle': '7-Day Wellness Challenge',
    'team.challengeDesc': 'Build your health habits and join the challenge',
    'team.joinChallenge': 'Join now!',
    'team.leaderboard': 'Leaderboard',
    'team.myTeam': 'My Team',
    'team.allTeams': 'All Teams',
    'team.challenges': 'Challenges',

    // Food Recognition
    'food.title': '🍽️ Food Recognition',
    'food.loading': 'Loading model...',
    'food.openCamera': '📷 Open Camera',
    'food.selectImage': '🖼️ Select Image',
    'food.capture': '📸 Take Photo',
    'food.cancel': 'Cancel',
    'food.analyzing': 'Analyzing...',
    'food.results': 'Results:',
    'food.retake': 'Retake',
    'food.save': 'Save Data',
    'food.logMeal': 'Log This Meal',
    'food.mealLogged': 'Meal logged successfully',
    'food.padthai': 'Pad Thai',
    'food.khaoManGai': 'Chicken Rice',
    'food.greenCurry': 'Green Curry',
    'food.friedRice': 'Fried Rice',
    'food.papayaSalad': 'Papaya Salad',
    'food.basilFry': 'Basil Stir-fry',
    'food.khaoSoi': 'Khao Soi Noodle',
    'food.larbMoo': 'Spicy Pork Salad',
    'food.tomYum': 'Tom Yum Shrimp Soup',
    'food.omelletRice': 'Omelet Rice',

    // Activity Page
    'activity.title': 'Activity Tracking',
    'activity.back': 'Back',
    'activity.minutesToday': 'Minutes Today',
    'activity.caloriesBurned': 'Calories Burned',
    'activity.quickLog': 'Quick Log',
    'activity.walking': 'Walking',
    'activity.running': 'Running',
    'activity.cycling': 'Cycling',
    'activity.strength': 'Strength',
    'activity.yoga': 'Yoga',
    'activity.swimming': 'Swimming',
    'activity.history': 'Activity History',
    'activity.noActivities': 'No activities logged yet',
    'activity.minutes': 'min',
    'activity.kcal': 'kcal',
    'activity.logActivity': 'Log Activity',
    'activity.duration': 'Duration',
    'activity.estimatedCalories': 'Estimated Calories',
    'activity.logButton': 'Log Activity',

    // Sleep Page
    'sleep.title': 'Sleep Tracking',
    'sleep.back': 'Back',
    'sleep.avgHours': 'Avg Hours/Week',
    'sleep.avgQuality': 'Avg Quality',
    'sleep.tipTitle': 'Sleep Tip',
    'sleep.tip1': 'Start logging your sleep to track your health',
    'sleep.tip2': 'You\'re sleeping too little. Aim for 7-9 hours per night',
    'sleep.tip3': 'Your sleep quality is low. Try avoiding screens before bed',
    'sleep.tip4': 'You\'re sleeping too much. This may affect your energy',
    'sleep.tip5': 'Excellent! Keep maintaining this sleep pattern',
    'sleep.logSleep': 'Log Sleep',
    'sleep.history': 'Sleep History',
    'sleep.noLogs': 'No sleep logs yet',
    'sleep.bedtime': 'Bedtime',
    'sleep.waketime': 'Wake Time',
    'sleep.duration': 'Duration',
    'sleep.hours': 'hours',
    'sleep.quality': 'Sleep Quality',
    'sleep.excellent': 'Excellent',
    'sleep.good': 'Good',
    'sleep.fair': 'Fair',
    'sleep.poor': 'Poor',
    'sleep.logButton': 'Log Sleep',

    // Longevity Score
    'longevity.title': 'Daily Longevity Score',
    'longevity.score': 'Score',
    'longevity.today': 'Today',
    'longevity.breakdown': 'Score Breakdown',
    'longevity.nutrition': 'Nutrition',
    'longevity.fasting': 'Fasting',
    'longevity.activity': 'Activity',
    'longevity.sleep': 'Sleep',
    'longevity.excellent': 'Excellent',
    'longevity.good': 'Good',
    'longevity.fair': 'Fair',
    'longevity.needsImprovement': 'Needs Improvement',
    'longevity.noData': 'No data yet',
    'longevity.startTracking': 'Start tracking your health data',
  },
};

